### PR TITLE
Added Search Criteria Summary component

### LINKED ISSUE #75: Search criteria summary
As a user search for things, i want to know what criteria the current search was performed on, so i can tell what the results presented represent

Expanation text saying

Showing results for "Food in Wairarapa"

### PR DESCRIPTION
**Pull request by JacOng17**
Added Search Criteria Summary component

Closed #75

### CODE REVIEW

**Comment by JacOng17** [comment]
search criteria

**Comment by Br3nda** [comment]
This pull request **introduces 1 alert** when merging 0782f60fa81cf8d340a851032f5b086b3bff240c into 98b5d593a767818735bd65fe3855dae624cf7409 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-ecb55cc4d6cc7cf1e31b7f92382a56a98380083a)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **introduces 1 alert** when merging bf109ce68116113525a19133063166ab5eacf50e into f0be4555be6b9d8b57a3caff3a6adb1bdd193f97 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-2681273a690626ef86c04509e13dc878ac3d23e0)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by mischa-s** [comment]
@JacOng17  I was a bit premature in approving this, the screen shot looked so good it blinded me, this is missing the file `pages/index.js`

**Pull request merged**
