### PR TITLE
Incomplete results

### LINKED ISSUE #185: Searchinator delivering incomplete results
Searchinator is not delivering comparable results to the Family Services Directory

### PR DESCRIPTION
**Pull request by dlouise64**
closes #185 

requires #236

NO in spreadsheet should now work.
[OHF Spreadsheet](https://github.com/ServiceInnovationLab/FSD/files/3027374/OHF.xlsx)

### CODE REVIEW

**Comment by Br3nda** [comment]
This pull request **introduces 1 alert** when merging cca5f882f66a32460a72563ae08477bf5cf10e49 into d0a366caf82e47231c3d0b2447d9d8b703dabbd5 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-c574674b6538b7a48c6f0cd345e3540eccc49e15)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by dlouise64** [comment]
@dlouise64 Tested again, working.

**Comment by Br3nda** [comment]
This pull request **introduces 1 alert** when merging db48c0e623129ff8e574409c3f64bf1ba899caf7 into 1cc4fc1bfe72e4e5b7622951fccdbeb759d63f9a - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-6c054befd9257c19956e406f04453ea18883c256)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **introduces 1 alert** when merging d612f769b11ed15d871c0d1e2a6d174bdc155f72 into ed0d47f4e99586b2f3884380b2d997aeb611f498 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-9979a79d7b6f0e33f642bcc30ad60e849e9e3051)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **introduces 1 alert** when merging 8e2114b357b213148e3fa1cb4646897b40a4d050 into 7c5a91e14a72a96957beacbc764f75ef762628dd - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-896904c2815d65d1713a47a6274ea9fc312dc5db)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
