### PR TITLE
Added feature to number results when needed.

### PR DESCRIPTION
**Pull request by JacOng17**
Added feature to number results when needed.

Closes #229

### CODE REVIEW

**Comment by JacOng17** [comment]
This should be added in the `.env` file: REACT_APP_DISPLAY_INDEX=true

**Comment by dlouise64** [comment]
@JacOng17 I will re review when you've pushed up the .env and new changes :)

**Comment by dlouise64** [comment]
@JacOng17 Oops we forgot to add the new env variable to the env_example file :) once that's done I will approve.

**Comment by JacOng17** [comment]
@dlouise64 Have added the new line to the `example.env`

**Comment by JacOng17** [comment]
@choirboy07 @sarahneeson  There's nothing to be tested for this. Just able to see on the dev environment.

**Pull request merged**
