### PR TITLE
Button to download provder details as a VCARD

### LINKED ISSUE #56: Save a service providers details to my phone address book
As a user
I want to be able to save a service providers contact details to my phone
So I can access them whenever I need them

 A / C
- [ ] Research what formats are available for Android and iPhone
- [ ] Provide a recommendation to move forward
- [ ] Write up new stories

Notes:
Propose this is providing the provider as a VCARD.

Some people's devices might not understand what this is, but there's not much we can do about that.

### PR DESCRIPTION
**Pull request by Br3nda**
When you test this, use your phone.

You should be able to get to your dev instance from wifi

Need to know if phones understand the format. It's working on my Huawei.

closes #56

### CODE REVIEW

**Comment by Br3nda** [comment]
Has anyone got an iPhone?

**Comment by mischa-s** [comment]
Just tested on safari on an iphone 5s and it doesn't appear to be working

**Comment by mischa-s** [comment]
Tested on 6s safari, contact worked but generated 
image from ios 1
image from ios

**Comment by mischa-s** [comment]
Also on closer inspection on andriod the phone number doesn't appear to be saving, only the address and email
screenshot_20190214-105314

**Comment by lamorrison** [comment]
Chrome/Android 8.0.0 it downloads but says the format isn't supported. clicking on the link to download again has no effect

**Comment by Br3nda** [comment]
Maybe VCARD isn't the right approach

**Pull request merged**
