### PR TITLE
Feature/114 populate locations in google directions

### LINKED ISSUE #114: Auto-populate google maps directions
doable

"string should be URL-escaped"

### PR DESCRIPTION
**Pull request by lamorrison**
Populates the Google search directions with the user's location and the service location. Also works if the user's location isn't set, the Google directions page works nicely with and empty box to type a start location into.

Moderately extensive tests including some new types of step. Been having some interesting trouble with the browser dropping requests during the cucumber tests so for example the address autosuggestions don't populate properly sometimes.

closes #114

### CODE REVIEW

**Comment by Br3nda** [comment]
This pull request **introduces 3 alerts** and **fixes 1** when merging 94a5deba89742507cac8691782de743a69efcdfb into ded9435d497f81d3a5e2ed993f24d8941b7d5fd4 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-c5f927ba88c5856db0e00db3bb5e4c69764c978e)

**new alerts:**

* 1 for Identical operands
* 1 for Useless conditional
* 1 for Missing variable declaration

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
is this for #114?

**Comment by Br3nda** [comment]
Adding the "closes #114" . Remove if i was wrong

**Comment by Br3nda** [comment]
This pull request **introduces 3 alerts** and **fixes 1** when merging 94a5deba89742507cac8691782de743a69efcdfb into a6986bf45fbac58aae7692a9072530cff4320f16 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-61ea92a674e0f89d31d7f2dfc6e1d32ee487108c)

**new alerts:**

* 1 for Identical operands
* 1 for Useless conditional
* 1 for Missing variable declaration

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **introduces 3 alerts** and **fixes 1** when merging 917cdacaa4307bb9b106ed7920aa5a4cbe401802 into a9ebacd46874c857b1147400dddeaaaa9fd17b64 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-09f5cf322ead4b61d9bdea17dea5b46e2b5928fd)

**new alerts:**

* 1 for Identical operands
* 1 for Useless conditional
* 1 for Missing variable declaration

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **introduces 3 alerts** and **fixes 1** when merging 31883d8df756249ff42f41e09141b56ec49dc45c into 2fc51e076c3e69c448557021ab59d31eba44eac2 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-711dd0c0eb04d4214580ab4264452f93dec2b669)

**new alerts:**

* 1 for Identical operands
* 1 for Useless conditional
* 1 for Missing variable declaration

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **introduces 3 alerts** and **fixes 1** when merging 2e3e30176743d39cfc0f6a5d0f4499cc978043d6 into 4cea00dc2615a381369f9326dcf9ba301132955c - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-b1a0f68bf00ad19aba6d5c622792a0d5f345e879)

**new alerts:**

* 1 for Identical operands
* 1 for Useless conditional
* 1 for Missing variable declaration

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging feb82595a76cdccba4073e50720167aa3850a606 into 4cea00dc2615a381369f9326dcf9ba301132955c - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-aa79abda6b5f53efc043b023e25f194d3b7ce7bb)

**new alerts:**

* 1 for Missing variable declaration

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 44e3a5c80e0e4fca0b836ede0764130e3f4e4352 into 4cea00dc2615a381369f9326dcf9ba301132955c - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-d3d71f86ccabf49173836601e81c2988f784cd5d)

**new alerts:**

* 1 for Missing variable declaration

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging b5d34da18a1a18a15be912dbe2b937349dbb1683 into 4cea00dc2615a381369f9326dcf9ba301132955c - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-452c62db89018d467eaa42ba10dab89bafef77ac)

**new alerts:**

* 1 for Missing variable declaration

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 9cd57a46f14a3b47d977cdbe984929252dc5b5a5 into 6002be311ab7c5cff7815f513fa808d60ac51810 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-96358e353a53d3b178467e47a20655b7fba539f5)

**new alerts:**

* 1 for Missing variable declaration

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **fixes 1 alert** when merging 996fa8c1444e84e3f15a5168fecbbd27a55165da into 6002be311ab7c5cff7815f513fa808d60ac51810 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-657103f1e0c2dfbaf61adff61ccb449ad0c75a3a)

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
This pull request **fixes 1 alert** when merging 41a0aaff31c215719c33eac0f1e034b2d9c51cf6 into 534effc3d673fa340eabd5fbb37970133d5dca78 - [view on LGTM.com](https://lgtm.com/projects/g/ServiceInnovationLab/FSD/rev/pr-1b0efe4945e0b0f8c5e86ea68cfeb2f3e605161d)

**fixed alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by JacOng17** [comment]
Works for me :smile: 
With Location
No Location

**Comment by Br3nda** [comment]
The address that ends up being used for the addresses isn't exactly the same

e.g. if I search for services near 1 queen street, Kopu", and pick a service, the direction in google us "16 Queen street kopu".

I think this is because we're passing the long/lat through to google, and google then resolves that down to an address and gets a different property. We have 7 decimal points on our long/lat, but that isn't always enough to narrow it down to one property when they are right next to each other.

Is this close enough for our purposes? Is it possible to pass the address instead of the long lat? What's the gotchas?

**Pull request merged**
